### ISSUE TITLE
How to remove the images?

### ISSUE THREAD

**Issue by ubersol** [itaysk/kube-imagepuller#1]
Hello, I hope this is the right place to ask the question. This is a great chart by the way!

But what if I wanted to remove the image I downloaded from all of my nodes? How do I manage to do that ?

**Comment by itaysk** [comment]
Hi, thanks for taking the time to open an issue!
This is not possible currently. The better thing to do for this project is to rewrite it as a CRD/controller and then more features could be supported. My original plan was to put this simple chart out there and see if there's interest in the problem domain, if there was I'd invest more time in this. Currently it doesn't look like it's clicking with many people though...

**Comment by ubersol** [comment]
hi there! ok thank you for your reply and time, I could remove the images manually by logging into the nodes and executing docker rmi, but wanted to make sure before going that kind of route the possibility of using your awesome chart doing the same thing :) .

**Comment by itaysk** [comment]
I don't think you should log into nodes in order to remove images. If you are worried about images filling up the disk space, this is handled by Kubernetes' built-in image garbage collector. see here: https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/#image-collection
